name: Build

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
  
    strategy:
      matrix:
        configuration: ["ReleaseR21","ReleaseR22", "ReleaseR23","ReleaseR24"]
        
    runs-on: windows-latest  
    
    env:
      SOLUTION_FILE_PATH: ScaleBars.sln 
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Restore the application
      run: msbuild $env:SOLUTION_FILE_PATH /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
     
    - name: Build the solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      #run: dotnet build --configuration ${{ matrix.configuration }} ${{env.SOLUTION_FILE_PATH}}
      run: msbuild /m /p:Configuration=${{env.Configuration}} ${{env.SOLUTION_FILE_PATH}}
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: ScaleBars\Bin\
        # Customize Artifact Retention Period
        retention-days: 1
      
  installer:
  
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        # Artifact name
        name: Release
        # Destination path
        path: ScaleBars\Bin\
    
    - name: Advanced Installer Tool
      # You may pin to the exact commit or the version.
      # uses: Caphyon/advinst-github-action@784f9ea25045e7458e8d08391703e7c5f17c5be4
      uses: Caphyon/advinst-github-action@v1.0
      with:
        advinst-enable-automation: 'true'
        aip-path: ${{ github.workspace }}\Installer\ScaleBars.aip

    - name: Publish setup artifact
      uses: actions/upload-artifact@v2
      with:
        name: setup
        path: ${{ github.workspace }}\Installer\ScaleBars-SetupFiles\ScaleBars.msi
      
