name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
  
    strategy:
      matrix:
        configuration: ["Release R21"]
        #configuration: ["Release R21","Release R22", "Release R23","Release R24"]
    
    runs-on: windows-latest  
    
    env:
      SOLUTION_FILE_PATH: ScaleBars.sln 
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Restore the application
      run: msbuild $env:SOLUTION_FILE_PATH /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
    #- name: Restore NuGet packages
    #  working-directory: ${{env.GITHUB_WORKSPACE}}
    #  run: nuget restore ${{env.SOLUTION_FILE_PATH}} 
     
    - name: Build the solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      env:
        Configuration: ${{ matrix.configuration }}
      
      
